# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        ('ecommerce', '0004_auto_20160822_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=400)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('spam_text', models.TextField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopelectro_category', to='pages.Page')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shopelectro.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecommerce.Order')),
                ('payment_option', models.CharField(choices=[('cash', 'Наличные'), ('cashless', 'Безналичные и денежные переводы'), ('AC', 'Банковская карта'), ('PC', 'Яндекс.Деньги'), ('GP', 'Связной (терминал)'), ('AB', 'Альфа-Клик'), ('MC', 'Мобильный телефон')], default='cash', max_length=255)),
            ],
            bases=('ecommerce.order',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(blank=True, null=True)),
                ('in_stock', models.PositiveIntegerField(default=0)),
                ('is_popular', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('purchase_price', models.FloatField(default=0)),
                ('wholesale_small', models.FloatField()),
                ('wholesale_medium', models.FloatField()),
                ('wholesale_large', models.FloatField()),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopelectro.Category')),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopelectro_product', to='pages.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_numeric', models.SmallIntegerField(default=0)),
                ('value', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopelectro.Product')),
            ],
        ),
    ]
