# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 07:55
# TODO need squashing this migration https://goo.gl/aohgCq
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0002_remove_category_spam_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('cash', 'Наличные'), ('cashless', 'Безналичные и денежные переводы')], default='cash', max_length=255),
        ),
    ]
