# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0003_auto_20160909_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_option',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличные'), ('cashless', 'Безналичные и денежные переводы'), ('AC', 'Банковская карта'), ('PC', 'Яндекс.Деньги'), ('GP', 'Связной (терминал)'), ('AB', 'Альфа-Клик'), ('MC', 'Мобильный телефон')], default='cash', max_length=255),
        ),
    ]
