# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-12 13:02
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings

from pages.models import Page


def create_custom_pages(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    apps.get_model('pages', 'Page').objects.using(db_alias)

    PageManager = apps.get_model('pages', 'Page').objects.using(db_alias)

    for fields in settings.PAGES:
        PageManager.get_or_create(type=Page.CUSTOM_TYPE, slug=fields['slug'], defaults=fields)


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0007_pages_data_migrations'),
    ]

    operations = [
        migrations.RunPython(create_custom_pages)
    ]
