# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-05 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0009_alter_product_and_category_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличные'), ('cashless', 'Безналичные и денежные переводы'), ('AC', 'Банковская карта'), ('PC', 'Яндекс.Деньги'), ('GP', 'Связной (терминал)'), ('AB', 'Альфа-Клик')], default='cash', max_length=255),
        ),
    ]
