# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-05 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0010_remove_mobile_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
