# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-10 14:26
from __future__ import unicode_literals

from django.db import migrations
from django.db.models.expressions import F

from pages.models import Page


def update_page_names(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    model_pages = apps.get_model(
        'pages', 'Page')._default_manager.using(db_alias).filter(type=Page.MODEL_TYPE)
    model_pages.update(name=F('h1'))
    model_pages.update(h1='')


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0010_alter_payment_type'),
        ('pages', '0007_rename_private_field'),
    ]

    operations = [
        migrations.RunPython(update_page_names),
    ]
