# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-14 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0010_auto_20161205_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(db_index=True, max_length=255)),
                ('rating', models.PositiveIntegerField(db_index=True, default=1)),
                ('dignities', models.TextField(blank=True, default='')),
                ('limitations', models.TextField(blank=True, default='')),
                ('general', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_feedbacks', to='shopelectro.Product')),
            ],
        ),
    ]
