# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-16 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0011_h1_to_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('rating', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('dignities', models.TextField(blank=True, default='')),
                ('limitations', models.TextField(blank=True, default='')),
                ('general', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopelectro.Category'),
        ),
        migrations.AddField(
            model_name='productfeedback',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_feedbacks', to='shopelectro.Product'),
        ),
    ]
