# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-20 11:05
from __future__ import unicode_literals

import django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0012_create_feedback'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
