# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0016_alter_price_and_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shopelectro.Category', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopelectro.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='in stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is popular'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, db_index=True, default=0, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.FloatField(default=0, verbose_name='purchase_price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='shopelectro.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_large',
            field=models.FloatField(default=0, verbose_name='wholesale_large'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_medium',
            field=models.FloatField(default=0, verbose_name='wholesale_medium'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_small',
            field=models.FloatField(default=0, verbose_name='wholesale_small'),
        ),
        migrations.AlterField(
            model_name='productfeedback',
            name='date',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='productfeedback',
            name='dignities',
            field=models.TextField(blank=True, default='', verbose_name='dignities'),
        ),
        migrations.AlterField(
            model_name='productfeedback',
            name='general',
            field=models.TextField(blank=True, default='', verbose_name='limitations'),
        ),
        migrations.AlterField(
            model_name='productfeedback',
            name='limitations',
            field=models.TextField(blank=True, default='', verbose_name='limitations'),
        ),
        migrations.AlterField(
            model_name='productfeedback',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='productfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='taggroup',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='taggroup',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, verbose_name='position'),
        ),
    ]
