# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-31 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0017_auto_20170321_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.SmallIntegerField(default=0, verbose_name='vendor_code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.SmallIntegerField(verbose_name='vendor_code'),
        ),
    ]
