# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 07:36
from __future__ import unicode_literals

from django.db import migrations, models
from shopelectro.models import Tag


def migrate_forward(apps, schema_editor):
    for tag in Tag.objects.all():
        print('Generating slug for "{0}" tag'.format(tag.name))
        tag.save() # will trigger slug update


def migrate_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0018_product_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=None, null=True, blank=True),
        ),
        migrations.RunPython(
            migrate_forward,
            migrate_backward,
        ),
    ]
