# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0019_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_description_template',
            field=models.TextField(default=''),
        ),
    ]
