# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0020_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
