# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-15 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_add_validation_to_template'),
        ('shopelectro', '0022_page_templates_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedModelTPage',
            fields=[
            ],
            options={
                'abstract': False,
                'proxy': True,
            },
            bases=('pages.page',),
        ),
    ]
