# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-10 01:38
from __future__ import unicode_literals

from django.db import migrations
from pages.models import CustomPage


def migrate_forward(apps, schema_editor):
    robots = CustomPage.objects.filter(slug='robots').first()
    if robots:
        robots.slug = 'robots.txt'
        robots.save()


def migrate_backward(apps, schema_editor):
    robots = CustomPage.objects.filter(slug='robots.txt').first()
    if robots:
        robots.slug = 'robots'
        robots.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0023_excludedmodeltpage'),
    ]

    operations = [
        migrations.RunPython(migrate_forward, migrate_backward),
    ]
