# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-23 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0024_update_robots_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('name', 'group')]),
        ),
    ]
