# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-24 08:44
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_forward(apps, schema_editor):
    Product = apps.get_model('shopelectro', 'Product')

    uuids_to_delete = [
        result['uuid'] for result in
        Product.objects.values('uuid').annotate(models.Count('uuid'))
        .order_by().filter(uuid__count__gt=1)
    ]

    preserved = set()

    for product in Product.objects.filter(uuid__in=uuids_to_delete):
        if product.uuid in preserved:
            product.delete()
        else:
            preserved.add(product.uuid)


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0025_tag_unique_constraint'),
    ]

    operations = [
        migrations.RunPython(migrate_forward),
    ]
