# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-21 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0026_remove_product_duplications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='name'),
        ),
    ]
