# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-29 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0029_increase_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='revenue',
            field=models.FloatField(default=0, null=True, verbose_name='revenue'),
        ),
    ]
