# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-11 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0030_order_revenue_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='name'),
        ),
    ]
