# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0034_index_tag_alphanumeric_name_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_pack',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='in pack'),
        ),
    ]
