# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-04 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0035_product_in_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixBlock',
            fields=[
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='matrix_block', serialize=False, to='shopelectro.Category', verbose_name='category')),
                ('block_size', models.PositiveSmallIntegerField(null=True, verbose_name='block size')),
            ],
            options={
                'verbose_name': 'Matrix block',
                'verbose_name_plural': 'Matrix blocks',
                'ordering': ['category__page__position', 'category__name'],
            },
        ),
    ]
