# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-27 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopelectro', '0037_populate_matrixblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='revenue',
        ),
    ]
