FROM fidals/se:dev

RUN pip install gunicorn

COPY ./etc/gunicorn.py /etc/

COPY . .

# drone already built static to this folder at previous step.
# See npm section of `.drone.yml` file
COPY ./front_build ./front_build
# built frontend files are required
RUN /bin/bash -c '[ "$(ls -A front_build)" ] || exit 1'
