FROM python:3.7-slim

RUN apt-get update \
    # wget is needed for working with ftp
    # git is needed for pip
    && apt-get install --no-install-recommends --no-install-suggests -y wget git make \
    && apt-get remove --purge -y git \
    && apt-get -y --purge autoremove \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/app/src/

COPY . .
RUN pip install -r requirements.txt
