FROM fidals/se:dev

RUN pip install gunicorn

COPY ./etc/gunicorn.py /etc/
# drone already built static to this folder at previous step.
# See npm section of `.drone.yml` file
COPY ./front/build ./front/build
