FROM python:3.6-slim

RUN apt-get update \
    # wget is needed for working with ftp
    # netcat is needed for waiting of postgres at `dc up -d app`
    && apt-get install --no-install-recommends --no-install-suggests -y wget git netcat \
    && apt-get -y --purge autoremove \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/app/src/

COPY . .
RUN pip install -r requirements.txt
