branches: master

workspace:
  base: /drone
  path: shopelectro/


pipeline:

#  python-build:
#    image: docker/compose:1.22.0
#    commands:
#      - cp shopelectro/settings/local.py.dist shopelectro/settings/local.py
#      - cd docker/
#      # Build python images with sources and static files
#      - docker-compose -f docker-compose-build.yml build python-dev
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    when:
#      event: [push, pull_request]

  docker-up:
    image: docker/compose:1.22.0
    commands:
      - cd docker
      - docker-compose rm postgres
      - cp drone_env/* env_files/
      - cp drone_env/.env .
      - docker-compose up -d app-drone
      - sleep 30
      - docker-compose logs app-drone
      - docker-compose logs postgres
      - docker-compose exec -T app-drone bash -c "./docker/check-health.sh http://0.0.0.0:8000/"
      - docker-compose stop
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: [push, pull_request]
