version: '2'

services:

  python-dev:
    image: fidals/se:dev
    build:
      context: ../
      dockerfile: docker/images/python/Dockerfile.dev

  python-prod:
    image: fidals/se:prod
    build:
      context: ../
      dockerfile: docker/images/python/Dockerfile.prod

  nodejs:
    image: fidals/se-nodejs:dev
    build:
      context: ../
      args:
        - deps_dir=$DEPS_DIR
      dockerfile: docker/images/node/Dockerfile

  nginx:
    image: fidals/se-nginx:prod
    build:
      context: ../
      dockerfile: docker/images/nginx/Dockerfile
