"""
Django settings for shopelectro project.

Generated by 'django-admin startproject' using Django 1.9.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__))))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'gl9syc68r%rmb*1&yzz(4%cotfpb$dy&wkb_y5_d0*be0pfulq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'catalog',
    'mptt',
    'seo',
    'macros',
    'shopelectro',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shopelectro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'shopelectro.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'refarm.sqlite3'
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'front/build'),
    os.path.join(BASE_DIR, 'static/assets'),
]

# refarm-blog config
# Each post type can have it's own alias
# For config below, page types will have different urls:
# - article: /blog/1/
# - news: /blog/news/1/
# - navigation: /blog/navigation/1/
# All aliases in config will be trimmed with "/" symbol
APP_BLOG_POST_TYPES = {
    'article': {'name': 'Статьи', 'alias': '', 'default': True},
    'news': {'name': 'Новости', 'alias': 'news'},
    'navigation': {'name': 'Навигация', 'alias': 'navigation'},
}

# Top products for main page
TOP_PRODUCTS = [291, 438, 1137, 2166, 2725, 2838, 3288, 3642, 3884, 3959]

CATEGORY_TILE = {
    'accumulators': [
        {'id': 1, 'name': 'Типоразмера ААА', 'alias': 'Текст'},
        {'id': 1, 'name': 'Для радиомоделей и игрушек', 'alias': 'Текст'},
        {'id': 1, 'name': 'Свинцово-кислотные', 'alias': 'Текст'},
        {'id': 1, 'name': 'Внешние универсальные', 'alias': 'Текст'},
        {'id': 1, 'name': 'Для ноутбуков', 'alias': 'Текст'},
        {'id': 1, 'name': 'Адаптеры, отсеки и футляры', 'alias': 'Текст'},
    ],
    'inverter': [
        {'id': 1, 'name': 'Инверторы СОЮЗ', 'alias': 'Текст'},
        {'id': 1, 'name': 'Инверторы ROBITON', 'alias': 'Текст'},
        {'id': 1, 'name': 'Преобразователи DC 24 В/12 В KALLER', 'alias': 'Текст'},
    ],
    'batteries': [
        {'id': 1, 'name': 'Типоразмера АА', 'alias': 'Текст'},
        {'id': 1, 'name': 'Часовые', 'alias': 'Текст'},
        {'id': 1, 'name': 'Литиевые', 'alias': 'Текст'},
    ],
    'lights': [
        {'id': 1, 'name': 'Фотон', 'alias': 'Текст'},
        {'id': 1, 'name': 'Эра', 'alias': 'Текст'},
        {'id': 1, 'name': 'Яркий Луч', 'alias': 'Текст'},
    ],
    'chargers': [
        {'id': 1, 'name': 'Для фотоаппаратов', 'alias': 'Текст'},
        {'id': 1, 'name': 'Для видеокамер', 'alias': 'Текст'},
        {'id': 1, 'name': 'Для свинцовых', 'alias': 'Текст'},
    ],
    'multimeters': [
        {'id': 1, 'name': 'MY68 Master Professional', 'alias': 'Текст'},
        {'id': 1, 'name': 'MY67 Master Professional', 'alias': 'Текст'},
        {'id': 1, 'name': 'MY65 Master Professional', 'alias': 'Текст'},
    ],
    'adapters': [
        {'id': 1, 'name': '220В для ноутбуков', 'alias': 'Текст'},
        {'id': 1, 'name': '12В для ноутбуков', 'alias': 'Текст'},
        {'id': 1, 'name': 'Трансформаторные', 'alias': 'Текст'},
    ],
}

FOOTER_LINKS = {
    'services': [
        {'id': 1, 'name': 'Ремонт аккумуляторов', 'alias': 'Текст'},
        {'id': 1, 'name': 'Пайка на заказ', 'alias': 'Текст'},
    ],
    'articles': [
        {'id': 1, 'name': 'Аккумуляторная батарея', 'alias': 'Текст'},
        {'id': 1, 'name': 'Нанопроводниковый аккумулятор', 'alias': 'Текст'},
        {'id': 1, 'name': 'Стационарные свинцовые аккумуляторы', 'alias': 'Текст'},
        {'id': 1, 'name': 'Батарейка типа АА', 'alias': 'Текст'},
    ],
    'about': [
        {'id': 1, 'name': 'Реквизиты', 'alias': 'Текст'},
        {'id': 1, 'name': 'Нормативные документы', 'alias': 'Текст'},
        {'id': 1, 'name': 'Оптовым покупателям', 'alias': 'Текст'},
        {'id': 1, 'name': 'Гарантии и возврат', 'alias': 'Текст'},
        {'id': 1, 'name': 'Карта сайта', 'alias': 'Текст'},
    ],
}

HREFS = {
    'istok_plus': 'http://istok-plus.ru',
}

CRUMBS = {
    'main': 'Главная',
    'catalog': 'Каталог',
    'blog': 'Список страниц',
}

from .local import *
